[versions]
accompanist = "0.27.1"
activity = "1.6.1"
compose = "1.4.0-alpha02"
compose-compiler = "1.3.1"
core = "1.9.0"
datastore = "1.0.0"
gradle = "8.0.0-alpha08"
kotlin = "1.7.10"
lifecycle = "2.5.1"
material3 = "1.1.0-alpha02"
twitter-detekt = "0.0.26"
detekt = "1.22.0"
hilt = "2.44.2"
hilt-viewmodel = "1.0.0"

[libraries]
accompanist-navigation-animation = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "accompanist" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
activity = { module = "androidx.activity:activity-compose", version.ref = "activity" }
compose-animation = { module = "androidx.compose.animation:animation", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-icons = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
compose-material3-window = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "material3" }
compose-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
core = { module = "androidx.core:core-ktx", version.ref = "core" }
datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
lifecycle = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
twitter-detekt = { module = "com.twitter.compose.rules:detekt", version.ref = "twitter-detekt" }
hilt-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-viewmodel = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-viewmodel" }

[plugins]
android-application = { id = "com.android.application", version.ref = "gradle" }
android-library = { id = "com.android.library", version.ref = "gradle" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }

