[versions]
gradle = "8.0.0-alpha02"
kotlin = "1.7.10"
core = "1.9.0"
lifecycle = "2.5.1"
activity = "1.6.0"
compose = "1.3.0-beta03"
material3 = "1.0.0-beta03"
accompanist = "0.26.4-beta"

[libraries]
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
core = { module = "androidx.core:core-ktx", version.ref = "core" }
lifecycle = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
activity = { module = "androidx.activity:activity-compose", version.ref = "activity" }
compose-animation = { module = "androidx.compose.animation:animation", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-icons = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
compose-material3-window = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "material3" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
compose-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
